name: CI/CD for Vercel API

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run basic tests
        run: npm test

      - name: Check JS syntax
        run: |
          echo "🔍 Checking JS syntax..."
          FILES=$(find api -type f -name "*.js")
          for file in $FILES; do
            echo "Checking $file"
            # ép Node thoát ngay khi lỗi, đồng thời hiển thị thông báo
            node --check "$file" || { echo "❌ Syntax error in $file"; exit 1; }
          done

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'
